# Install XCode via Mac App Store first
# Run `brew tap homebrew/bundle` to brew `brew bundle`
# Run `brew bundle` to brew the list below

# Install Cask
brew "caskroom/cask/brew-cask"

## CLI Tools
brew "ack"
brew "ansible"
brew "brew-cask"
brew "docker"
brew "emacs"
brew "fasd"
brew "findutils"
brew "freetds"
brew "git"
brew "go"
brew "gradle"
brew "graphviz"
brew "imagemagick"
cask "java"
brew "jq"
brew "jruby"
brew "leiningen"
brew "md5sha1sum"
brew "mercurial"
brew "nmap"
brew "node"
brew "openssl"
brew "p7zip"
brew "packer"
brew "parallel"
brew "pypy"
brew "python"
brew "python3"
brew "rbenv"
brew "redis"
brew "ruby-build"
brew "ruby-install"
brew "samba"
brew "selecta"
brew "sloccount"
brew "sqlite"
brew "ssh-copy-id"
#brew "sshpass"
brew "http://git.io/sshpass.rb"
brew "the_silver_searcher"
brew "tmux"
brew "tree"
brew "unrar"
brew "watch"
brew "wget"
brew "zeromq"

## GUI Tools
cask "alfred"
cask "caffeine"
cask "flux"
cask "dropbox"

cask "virtualbox"
cask "vagrant"
cask "vmware-fusion"

cask "google-chrome"
cask "firefox"

cask "iterm2"
cask "nvalt"
cask "spotify"
cask "slack"
cask "textexpander"
cask "1password"
cask "ynab"
cask "sonos"
cask "microsoft-office"
cask "caskroom/versions/sublime-text3"
cask "omnifocus"
cask "transmit"

